package com.example.softwareg14.map;

public enum Error {
    MISSING_USERNAME,
    MISSING_PASSWORD,
    MISSING_EMAIL,
    MISSING_NAME,
    MISSING_PHONE,
    MISSING_DESCRIPTION,
    MISSING_DURATION,
    MISSING_PRICE,
    MISSING_IMAGE,
    MISSING_LOCATION,
    MISSING_CATEGORY,
    MISSING_ORGANIZATION,
    MISSING_MAX_CAPACITY,
    MISSING_DATE,
    MISSING_ID,
    MISSING_ADDRESS,
    MISSING_WEBSITE,
}
